//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCAssign.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CDACEntities1 : DbContext
    {
        public CDACEntities1()
            : base("name=CDACEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bhagyesh_Admin> Bhagyesh_Admin { get; set; }
        public virtual DbSet<Bhagyesh_User> Bhagyesh_User { get; set; }

        public System.Data.Entity.DbSet<MVCAssign.Models.UserLogin> UserLogins { get; set; }
    }
}
